#if !canImport(ObjectiveC)
import XCTest

extension BitStorageBoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitStorageBoolTests = [
        ("testInit", testInit),
        ("testReadUnderlying", testReadUnderlying),
        ("testWrite", testWrite),
    ]
}

extension BitStorageMemoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitStorageMemoryTests = [
        ("testARC", testARC),
    ]
}

extension BitStorageSignedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitStorageSignedTests = [
        ("testSignExtension", testSignExtension),
        ("testSignRepresentationAndMask", testSignRepresentationAndMask),
    ]
}

extension BitStorageSubByteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitStorageSubByteTests = [
        ("testInitBounds", testInitBounds),
        ("testStorageAliasing", testStorageAliasing),
    ]
}

extension BitStorageUnsignedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitStorageUnsignedTests = [
        ("testInit", testInit),
        ("testReadUnderlying", testReadUnderlying),
        ("testWrite", testWrite),
    ]
}

extension MultiByteCoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MultiByteCoderTests = [
        ("testAdjacentSpan", testAdjacentSpan),
        ("testLittleEndian", testLittleEndian),
        ("testSingleByte", testSingleByte),
        ("testSpanning64BitUnsigned", testSpanning64BitUnsigned),
        ("testThreeByteSpan", testThreeByteSpan),
    ]
}

extension WordDescriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WordDescriptionTests = [
        ("testBitEncoding", testBitEncoding),
        ("testStorageWidth", testStorageWidth),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BitStorageBoolTests.__allTests__BitStorageBoolTests),
        testCase(BitStorageMemoryTests.__allTests__BitStorageMemoryTests),
        testCase(BitStorageSignedTests.__allTests__BitStorageSignedTests),
        testCase(BitStorageSubByteTests.__allTests__BitStorageSubByteTests),
        testCase(BitStorageUnsignedTests.__allTests__BitStorageUnsignedTests),
        testCase(MultiByteCoderTests.__allTests__MultiByteCoderTests),
        testCase(WordDescriptionTests.__allTests__WordDescriptionTests),
    ]
}
#endif
